#!/usr/bin/env bash 
#Scriptor: Shane Harder
#Date: 2025-10-6
# system-report.sh 
# Generates a concise system information report suitable for human consumption. 

echo "==========================================================================="

# Gather data 
HOSTNAME="$(hostname)" 
USERNAME="$(whoami)" 
DATETIME="$(date '+%Y-%m-%d %H:%M:%S')" 

echo "==========================================================================="

# OS 
if [ -r /etc/os-release ]; then 
  . /etc/os-release 
  OS="${NAME} ${VERSION}" 
else 
  OS="$(uname -s) $(uname -r)" 
fi 

# Uptime 
UPTIME="$(uptime -p | sed 's/^up //')" 

# CPU 
CPU="$(awk -F: '/model name/ {print $2; exit}' /proc/cpuinfo | sed 's/^[ \t]*//')" 
if [ -z "$CPU" ]; then 
  CPU="$(lscpu 2>/dev/null | awk -F: '/Model name/ {print $2; exit}' | sed 's/^[ \t]*//')" 
fi 

# RAM 
RAM="$(free -h --si | awk '/^Mem:/ {print $2 " total"}')" 

# Disks: show model and size where available 
DISKS="$(lsblk -dn -o NAME,TYPE | awk '$2=="disk" {print $1}' | while read -r dev; do 
  DEVPATH="/dev/$dev" 
  MODEL="$(cat /sys/block/"$dev"/device/model 2>/dev/null || echo UnknownModel)" 
  SIZE="$(lsblk -dn -o SIZE "$DEVPATH" 2>/dev/null || echo UnknownSize)" 
  printf "%s: %s %s\n" "$DEVPATH" "$MODEL" "$SIZE" 
done | paste -s -d';' -)" 

# Video: try lspci then lshw fallback 
VIDEO="$(lspci 2>/dev/null | grep -i 'vga\|3d\|display' | head -n1 | sed 's/^[^:]*: //')" 
if [ -z "$VIDEO" ]; then 
  VIDEO="$(lshw -c display 2>/dev/null | awk -F: '/product/ {p=$2} /vendor/ {v=$2} END {print (v?p?" "v"":"")p}' | sed 's/^[ \t]*//')" 
fi 
VIDEO="${VIDEO:-UnknownVideo}" 

# Host Address and Gateway 
DEFAULT_GW_IFACE="$(ip route show default 0.0.0.0/0 | awk '/default/ {print $5; exit}')" 
GATEWAY_IP="$(ip route show default | awk '/default/ {print $3; exit}')" 
if [ -n "$DEFAULT_GW_IFACE" ]; then 
  HOST_ADDR="$(ip -4 addr show dev "$DEFAULT_GW_IFACE" | awk '/inet / {print $2}' | cut -d/ -f1 | head -n1)" 
else 
  HOST_ADDR="$(hostname -I | awk '{print $1}')" 
fi 
GATEWAY_IP="${GATEWAY_IP:-UnknownGateway}" 
HOST_ADDR="${HOST_ADDR:-UnknownAddress}" 

# DNS Server 
DNS_SERVER="$(systemd-resolve --status 2>/dev/null | awk '/DNS Servers:/ {print $3; exit}')" 
if [ -z "$DNS_SERVER" ]; then 
  DNS_SERVER="$(awk '/^nameserver/ {print $2; exit}' /etc/resolv.conf)" 
fi 
DNS_SERVER="${DNS_SERVER:-UnknownDNS}" 

# System Status 
USERS_LOGGED_IN="$(who | awk '{print $1}' | sort -u | paste -s -d, -)" 
USERS_LOGGED_IN="${USERS_LOGGED_IN:-none}" 

# Disk Space: list local filesystems (exclude tmpfs/devtmpfs) format: /mountpoint N 
DISK_SPACE="$(df -h --output=target,avail -x tmpfs -x devtmpfs -x squashfs | awk 'NR>1 {printf "%s %s;",$1,$2}' | sed 's/;$//')" 

# Process count 
PROCESS_COUNT="$(ps -e --no-headers | wc -l | tr -d ' ')" 

# Load averages 
LOAD_AVG="$(awk '{printf "%s, %s, %s", $1, $2, $3}' /proc/loadavg)" 

# Listening network ports 
LISTEN_PORTS="$(ss -lntu 2>/dev/null | awk 'NR>1 { split($5,a,":"); print a[length(a)] }' | grep -E '^[0-9]+$' | sort -n -u | paste -s -d, -)" 
LISTEN_PORTS="${LISTEN_PORTS:-none}" 

# UFW Status 
if command -v ufw >/dev/null 2>&1; then 
  UFW_STATUS="$(ufw status | sed -n '1p')" 
else 
  UFW_STATUS="ufw not installed" 
fi 
# Battery Health
BATTERY_INFO="No battery detected"
for bat in /sys/class/power_supply/BAT*; do
  if [ -d "$bat" ]; then
    NAME="$(basename "$bat")"
    STATUS="$(cat "$bat/status" 2>/dev/null || echo Unknown)"
    CAPACITY="$(cat "$bat/capacity" 2>/dev/null || echo Unknown)%"
    ENERGY_FULL="$(cat "$bat/energy_full" 2>/dev/null || cat "$bat/charge_full" 2>/dev/null || echo Unknown)"
    ENERGY_DESIGN="$(cat "$bat/energy_full_design" 2>/dev/null || cat "$bat/charge_full_design" 2>/dev/null || echo Unknown)"
    HEALTH="Unknown"
    if [ "$ENERGY_FULL" != "Unknown" ] && [ "$ENERGY_DESIGN" != "Unknown" ]; then
      HEALTH=$(awk -v full="$ENERGY_FULL" -v design="$ENERGY_DESIGN" 'BEGIN { if (design>0) printf("%.1f%%", (full/design)*100); else print "Unknown" }')
    fi
    BATTERY_INFO="Battery ${NAME}: Status=${STATUS}, Capacity=${CAPACITY}, Health=${HEALTH} (Full=${ENERGY_FULL}, Design=${ENERGY_DESIGN})"
    break
  fi
done



echo "==========================================================================="

# Output report with a blank line at start and end 
cat <<EOF 

System Report for ${HOSTNAME} generated by ${USERNAME}, on ${DATETIME} 

System Information 

------------------ 

OS: ${OS} 
Uptime: ${UPTIME} 
CPU: ${CPU} 
RAM: ${RAM} 
Disk(s): ${DISKS} 
Video: ${VIDEO} 
Host Address: ${HOST_ADDR} 
Gateway IP: ${GATEWAY_IP} 
DNS Server: ${DNS_SERVER} 

 System Status 

------------- 
Users Logged In: ${USERS_LOGGED_IN} 
Disk Space: ${DISK_SPACE} 
Process Count: ${PROCESS_COUNT} 
Load Averages: ${LOAD_AVG} 
Listening Network Ports: ${LISTEN_PORTS} 
UFW Status: ${UFW_STATUS} 
Battery: ${BATTERY_INFO}

EOF
echo "==========================================================================="
